blogproject/blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

# regular expression
app_name = 'blog'
urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$',login_required(views.PostDetailView.as_view()),name='detail'), # post/1
    # archives/2017/9/
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.ArchivesView.as_view(),name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$',views.TagView.as_view(),name='tag'),
    #url(r'^search/$',views.search,name='search'),
]

blogproject/blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog.feeds import AllPostRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')), # 所有blog/urls.py里的路由都有前缀'blog/'
    url(r'',include('comment.urls')),
    url(r'^all/rss/$',AllPostRssFeed(),name='rss'),
    url(r'search/',include('haystack.urls')),
    url(r'^accounts/',include('users.urls')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
]

blogproject/comment/urls.py
from django.conf.urls import url

from . import views

app_name = 'comment'
urlpatterns=[
    url(r'comment/post/(?P<post_pk>[0-9]+)/$',views.post_comment,name='comments'),
]

blogproject/blog/models.py
from django.db import models
from django.urls import reverse
# User是一个自带的模型类，里面是用户的字段
from django.contrib.auth.models import User
from markdown import Markdown
from django.utils.html import strip_tags

class Category(models.Model):
    name = models.CharField(max_length=64)
    # annotate产生的隐藏属性：num_posts

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=64)
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=64)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    # 摘要
    excerpt = models.CharField(max_length=256,blank=True)

    # 关系
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag,blank=True)

    author = models.ForeignKey(User)

    # 文章阅读量
    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.views+=1
        self.save(update_fields=['views'])

    # 看不到的属性：comment_set

    class Meta:
        ordering = ['-created_time','-modified_time']

    def get_absolute_url(self):
        #使用reverse函数，生成一个url，例如 post / 1
        return reverse('blog:detail',kwargs={'pk':self.pk}) #

    def save(self,*args,**kwargs):
        if not self.excerpt:
            md = Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:32]
        super().save(*args,**kwargs)

    def __str__(self):
        return self.title

blogproject/comment/models.py
from django.db import models

class Comment(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField(max_length=64)
    url = models.URLField(blank=True)

    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

blogproject/blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post,Category,Tag
from markdown import markdown,Markdown
from django.views.generic import ListView,DetailView
from django.db.models import Q
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension

from comment.forms import CommentForm
from django.http import HttpResponse

# def index(request):
#     post_list = Post.objects.all()
#     return render(request,'blog/index.html',context={'post_list':post_list})
#     # return HttpResponse('<h1>hello world</h1>')

class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list' # 这个name不能瞎取，必须和模板中的变量一直
    paginate_by = 1

    def pagination_data(self,paginator,page,is_paginated):
        if not is_paginated:
            return {}

        # 设置默认值
        # 1、first是首页
        first = False
        #\2、省略号
        left_has_more = False
        #\3、当前页左边的几个页码
        left = []
        # 4、当前页的页码
        page_number = page.number
        #\5、当前页右边的几个页码
        right = []
        #\6、省略号
        right_has_more = False
        #\7、last是最后一页
        last = False

        # 总页数
        total_pages = paginator.num_pages

        # 获取整个分页页码列表。例如共有10页时，page_range:[1,2,3,4,5,6,7,8,9,10]
        page_range = paginator.page_range

        # 如果当前是第1页
        if page_number == 1:
            right = page_range[page_number:page_number+1]
            if right[-1]<total_pages-1:
                right_has_more = True
            if right[-1]<total_pages:
                last = True
        elif page_number == total_pages: # 如果当前是最后一页
            left = page_range[(page_number-2) if (page_number-2)>0 else 0:page_number-1]
            if left[0]>2:
                left_has_more = True
            if left[0]>1:
                first = True
        else:
            left = page_range[(page_number-2) if (page_number-2)>0 else 0:page_number-1]
            right = page_range[page_number:page_number+1]
            if right[-1]<total_pages-1:
                right_has_more = True
            if right[-1]<total_pages:
                last = True
            if left[0]>2:
                left_has_more = True
            if left[0]>1:
                first = True
        data = {
            'left':left,
            'right':right,
            'left_has_more':left_has_more,
            'right_has_more':right_has_more,
            'first':first,
            'last':last,
        }

        return data

    def get_context_data(self, **kwargs):
        # 首先获得基类get_context_data()返回的context
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        pagination_data = self.pagination_data(paginator,page,is_paginated)

        context.update(pagination_data)

        return context





# def detail(request,pk):
#     post = get_object_or_404(Post,pk=pk)
#     post.increase_views()
#     post.body = markdown(post.body,extensions=[
#                          'markdown.extensions.extra',
#                          'markdown.extensions.codehilite',
#                          'markdown.extensions.toc',])
#     form = CommentForm()
#     comment_list = post.comment_set.all()
#     context = {
#         'post':post,
#         'form':form,
#         'comment_list':comment_list,
#     }
#     return render(request,'blog/detail.html',context=context)

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self,request,*args,**kwargs):
        response = super().get(request,*args,**kwargs)
        self.object.increase_views() # self.object实际上是Post的对象
        return response

    def get_object(self,queryset=None):
        post = super().get_object(queryset)
        md = Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),  # 把锚点修改为文章实际内容
        ])
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # 把post加到context
        form = CommentForm()
        # 下面的self.object是由self.get_object()得到的
        # 因此self.get_object()必须返回post
        comment_list = self.object.comment_set.all()
        context.update({   # context已有post了，所以这里使用更新update
            'form':form,
            'comment_list':comment_list,
        })
        return context








# def archives(request,year,month):
#     post_list = Post.objects.filter(created_time__year=year,
#                                     created_time__month=month)
#     return render(request,'blog/index.html',context={'post_list':post_list})


class ArchivesView(IndexView):
    def get_queryset(self):
        return super().get_queryset().filter(
            created_time__year = self.kwargs.get('year'),
            created_time__month = self.kwargs.get('month')
        )

# def category(request,pk):
#     cate = get_object_or_404(Category,pk=pk)
#     post_list = Post.objects.filter(category=cate)
#     return render(request,'blog/index.html',context={'post_list':post_list})

class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category,pk=self.kwargs.get('pk'))
        # 下面filter(category=cate)中的category是post.category
        return super().get_queryset().filter(category=cate)







class TagView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag,pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(tags=tag)




def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg='请输入关键词'
        return render(request,'blog/index.html',{'error_msg':error_msg})

    post_list = Post.objects.filter(Q(title__icontains=q)|Q(body__icontains=q))
    return render(request,'blog/index.html',{'post_list':post_list})

blogproject/templates/blog/base.html
{% load staticfiles %}
{% load blog_tags %}

<html>
<head>
    <meta charset="UTF-8">
    <title>
        {{title}}
    </title>

    <style>
        span.highlighted{
            color:red;
        }
    </style>

    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Black</b> &amp;White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="bsexample-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="fullwidth.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                            {% if user.is_authenticated %}
                                <li class="cl-effect-11"><a href="{% url 'password_change' %}">修改密码</a></li>
                                <li class="cl-effect-11"><a href="{% url 'logout' %}">Logout</a></li>

                            {% else %}
                                <li class="cl-effect-11"><a href="{% url 'login' %}">Login</a></li>
                            {% endif %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="searchicon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name='q' placeholder="搜索" required>
                            <button type="submit"><span class="ionios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock %}
            </main>

            <aside class="col-md-4">
                {% block toc %}
                {% endblock %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
                        </li>
                        {% empty %}
                        没有文章
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">{{date.year}}年{{date.month}}月</a>
                        </li>
                        {% empty %}
                        没有归档
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{category.name}}<span class="post-count">({{category.num_post}})</span> </a>
                        </li>
                        {% empty %}
                        没有分类
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">{{tag.name}}<span class="post-count">({{tag.num_posts}})</span></a>
                        </li>
                        {% empty %}
                        没有标签
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a></p>
            </div>
        </div>
    </div>
</footer>

<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ionios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>
<script src="{% static 'blog/js/script.js' %}"></script>
</body>
</html>

blogproject/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block main %}
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">{{ post.title }}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ post.author }}</a></span>
            <span class="comments-link"><a href="{{post.get_absolute_url}}#comment-area">{{post.comment_set.count}} 评论</a></span>
            <span class="views-count"><a href="#">{{post.views}} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        {{ post.body|safe }}
        <div class="widget-tag-cloud">
            <ul>
                <h3>标签</h3>
                {% for tag in post.tags.all %}
                <li>
                    <a href="{% url 'blog:tag' tag.pk %}">{{tag.name}}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</article>
<section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>
    <form action="{% url 'comment:comments' post.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <!--{# cross site request forgery #}-->
        <div class="row">
            <div class="col-md-4">
                <label for="{{form.name.id_for_label}}">名字：</label>
                {{form.name}}
                {{form.name.error}}
            </div>
            <div class="col-md-4">
                <label for="{{form.email.id_for_label}}">邮箱：</label>
                {{form.email}}
                {{form.email.error}}
            </div>
            <div class="col-md-4">
                <label for="{{form.url.id_for_label}}">网址：</label>
                {{form.url}}
                {{form.url.error}}
            </div>
            <div class="col-md-12">
                <label for="{{form.text.id_for_label}}">评论：</label>
                {{form.text}}
                {{form.text.error}}
                <button type="submit" class="comment-btn">发表</button>
            </div>
        </div> <!-- row -->
    </form>
    <div class="comment-list-panel">
        <h3>评论列表，共 <span>{{post.comment_set.count}}</span> 条评论</h3>
        <ul class="comment-list list-unstyled">
            {% for comment in comment_list %}
            <li class="comment-item">
                <span class="nickname">{{comment.name}}</span>
                <time class="submit-date" >{{comment.created_time}}</time>
                <div class="text">
                    {{comment.text}}
                </div>
            </li>
            {% empty %}
            无评论
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock main %}

{% block toc %}
<div class="widget widget-content">
    <h3 class="widget-title">文章目录</h3>
    {{post.toc | safe}}
</div>
{% endblock %}

blogproject/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block main %}
{% if error_msg %}
<p>{{error_msg}}</p>
{% endif %}
{% for post in post_list %}
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ post.author }}</a></span>
            <span class="comments-link"><a href="#">{{post.comment_set.count}} 评论</a></span>
            <span class="views-count"><a href="#">{{post.views}} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <p>{{ post.excerpt }}</p>
        <div class="read-more cl-effect-14">
            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
        </div>
    </div>
</article>
{% empty %}
<div class="no-post">暂时还没有发布的文章！</div>
{% endfor %}

{% if is_paginated %}
<div class="pagination">
    <ul>
        {% if first %}
        <li><a href="?page=1">1</a></li>
        {% endif %}
        {% if left %}
            {% if left_has_more %}
                <li><span>...</span></li>
            {% endif %}
            {% for i in left %}
                <li><a href="?page={{i}}">{{i}}</a> </li>
            {% endfor %}
        {% endif %}
        <li class="current"><a href="?page={{page_obj.number}}">{{page_obj.number}}</a></li>
        {% if right %}
            {% for i in right %}
                <li><a href="?page={{i}}">{{i}}</a></li>
            {% endfor %}
            {% if right_has_more %}
                <li><span>...</span></li>
            {% endif %}
        {% endif %}
        {% if last %}
            <li><a href="?page={{paginator.num_pages}}">{{paginator.num_pages}}</a></li>
        {% endif %}
    </ul>
</div>
{% endif %}


{% endblock main %}